name: pip_install

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: pip install ezdsp
      run: |
        pip install ezdsp
