name: run_example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: pip install umpy_fn and run example
      run: |
        pip install numpy_fn
        python ./example.py
